/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 * 
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with  
 * the terms contained in the written license agreement between you and ArcCore, 
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as 
 * published by the Free Software Foundation and appearing in the file 
 * LICENSE.GPL included in the packaging of this file or here 
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

/*
 *  General requirements
 */
/** @req CANTP160 */

/*
 * Definitions generated by tools
 */

//lint -save -e451 //PC-Lint Wrong interpretation, "Platform_Types.h included twice without a standard include guard."

#ifndef CANTP_TYPES_H_
#define CANTP_TYPES_H_

#include "Platform_Types.h"
#include "ComStack_Types.h"


typedef enum {
	CANTP_NOT_LAST_ENTRY, CANTP_END_OF_LIST
} CanTp_ListItemType;


typedef enum {
	CANTP_EXTENDED, 
	CANTP_STANDARD
} CanTp_AddressingFormantType;

typedef enum {
	CANTP_OFF, CANTP_ON
} CanTp_StateType;

typedef enum {
	CANTP_RX_WAIT,
	CANTP_RX_PROCESSING,
	CANTP_TX_WAIT,
	CANTP_TX_PROCESSING
} CanTp_TransferInstanceMode;


typedef enum {
	CANTP_FUNCTIONAL, CANTP_PHYSICAL
} CanTp_TaTypeType;

typedef enum {//onlye for FE-7
	CANTP_ADD_FUNCTIONAL = 0xDF,
	CANTP_ADD_PHYSICAL= 0xA0
} CanTp_ADD_Type;

typedef struct {
	const uint32_t CanTpNSa;
} CanTp_NSaType;

typedef struct {
	const uint32_t CanTpNTa; /* IMPROVEMENT Why is this 32-bit, can it be lowered */
} CanTp_NTaType;

typedef struct {
	const uint32_t CanTpRxNPduId; 
	const uint32_t CanTpRxNPduRef; 
} CanTp_RxNPduType; 

typedef struct {
	const uint32_t CanTpTxNPduId; /* NOTE: Remove this? */
	const uint32_t CanTpTxNPduRef; 
} CanTp_TxNPduType; 

typedef struct {
	const uint32_t CanTpTxFcNPduRef;  /* Reference to a PDU in the COM stack. */
} CanTp_TxFcNPduType; 

typedef struct {
	const uint32_t CanTpRxFcNPduRef;  /* Reference to a PDU in the COM stack. */
	const uint32_t CanTpRxFcNPduId; 
} CanTp_RxFcNPduType; 


typedef struct {
    const PduIdType CanTp_FcPduId; // When recieving this Pdu this conf can be used (if TA match in extended).
    const PduIdType CanIf_FcPduId; // The polite CanIf PDU index.
    const PduIdType PduR_PduId; // The polite PduR index.
    const CanTp_AddressingFormantType CanTpAddressingFormant;
    const uint8_t CanTpBs;  /* Sets the maximum number of messages of N-PDUs before flow control. */
    const uint16_t CanTpNar;  /* Timeout for transmission of a CAN frame (ms). */
    const uint16_t CanTpNbr;
    const uint16_t CanTpNcr;  /* Time out for consecutive frames (ms). */
    const uint8_t CanTpRxChannel;  /* Connection to runtime variable index, see CanTp 266. */
    const uint16_t CanTpRxDI;  /* Data length code for of this RxNsdu. */
    const CanTp_StateType CanTpRxPaddingActivation;  /* Enable use of padding. */
    const CanTp_TaTypeType CanTpRxTaType;  /* Functional or physical addressing. */
    const uint8_t CanTpWftMax;   /* Max number FC wait that can be transmitted consecutively. */
    const uint16_t CanTpSTmin;  /* Minimum time the sender shall wait between transmissions of two N-PDU. */
    /*const uint32_t							CanTpNSduRef ** req: CanTp241. This is PDU id - typeless enum. */
    const CanTp_NSaType *CanTpNSa;
    const CanTp_NTaType *CanTpNTa;
    //CanTp_RxNPduType *CanTpRxNPdu;
    //CanTp_TxFcNPduType *CanTpTxFcNPdu;
    //const PduIdType CanTpRxPduId;

} CanTp_RxNSduType; 

typedef struct {
	const PduIdType CanIf_PduId; // The polite CanIf index.
	const PduIdType PduR_PduId; // The polite PduR index.
	const PduIdType CanTp_FcPduId;
	const CanTp_AddressingFormantType CanTpAddressingMode; 
	const uint8_t CanTpBs;  /* add by mgd on 20210705 */
	const uint16_t CanTpNas;  /* N_As timeout for transmission of any CAN frame. */
	const uint16_t CanTpNbs;  /* N_Bs timeout of transmission until reception of next Flow Control. */
	const uint16_t CanTpNcs;  /* N_Bs timeout of transmission until reception of next Flow Control. */
	const uint8_t	CanTpTxChannel;  /* Link to the TX connection channel (why?). */
	const uint16_t CanTpTxDI;  /* Data length code for of this TxNsdu. */
	/*const uint32_t						CanTpTxNSduId; / ** req: CanTp268: Data length code for of this TxNsdu. */
	const CanTp_StateType CanTpTxPaddingActivation;  /* Enable use of padding. */
	const CanTp_TaTypeType CanTpTxTaType;  /* Functional or physical addressing. */
	/*const uint32_t						CanTpNSduRef ** req: CanTp261. This is PDU id - typeless enum. */
	const uint8_t CanTpWftMax;  /* add by mgd on 20210705. */
    const uint16_t CanTpSTmin;  /* add by mgd on 20210705 */
	const CanTp_NSaType *CanTpNSa;
	const CanTp_NTaType *CanTpNTa;
	//CanTp_RxFcNPduType *CanTpRxFcNPdu;
	//CanTp_TxNPduType *CanTpTxNPdu;
	//PduIdType CanTpTxPduId;

} CanTp_TxNSduType; 

// - - - - - - - - - - -

typedef struct {
	const uint32_t main_function_period;
	const uint32_t number_of_sdus;
	const uint32_t number_of_pdus;
	const uint8_t  padding;
	const uint8_t  start_of_txsdu;
	const uint8_t  start_of_txpdu;
} CanTp_GeneralType; 

// - - - - - - - - - - -

typedef enum {
	IS015765_TRANSMIT, ISO15765_RECEIVE
} CanTp_DirectionType;


// - - - - - - - - - - -

typedef struct {
	const CanTp_DirectionType direction;
	const CanTp_ListItemType listItemType;
	union {
		const CanTp_RxNSduType 	CanTpRxNSdu;
		const CanTp_TxNSduType 	CanTpTxNSdu;
	} configData;
} CanTp_NSduType;

typedef struct {
	const CanTp_AddressingFormantType CanTpAddressingMode;
	const PduIdType CanTpNSduIndex;
	const PduIdType CanTpReferringTxIndex;
} CanTp_RxIdType;

// - - - - - - - - - - -

/** Top level config container for CANTP implementation. */
typedef struct {
	
	const CanTp_GeneralType *CanTpGeneral; 

	
	const CanTp_NSduType *CanTpNSduList;

	const CanTp_RxIdType *CanTpRxIdList;


} CanTp_ConfigType;


#endif /* CANTP_TYPES_H_ */
