/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-24:09-38-31.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#ifndef DCM_CFG_H_
#define DCM_CFG_H_

#define DCM_VERSION_INFO_API              STD_ON
#define DCM_DEV_ERROR_DETECT              STD_OFF
#define DCM_RESPOND_ALL_REQUEST           STD_OFF  // Activate/Deactivate response on SID 0x40-0x7f and 0xc0-0xff.
#define DCM_REQUEST_INDICATION_ENABLED    STD_OFF  // Activate/Deactivate indication request mechanism.
#define DCM_PAGEDBUFFER_ENABLED           STD_OFF	// Enable/disable page buffer mechanism (currently only disabled supported)
#define DCM_DID_RESERVED_ENABLE			  STD_ON

#define DCM_DSL_BUFFER_LIST_LENGTH		2
#define DCM_DSL_TX_PDU_ID_LIST_LENGTH		7
#define DCM_DSL_RX_PDU_ID_LIST_LENGTH		8

#define DCM_MAIN_FUNCTION_PERIOD_TIME_MS	10


#define DCM_RX_vEcuC_Pdu_0 0   //
#define DCM_RX_vEcuC_Pdu_1 1   //
#define DCM_RX_vEcuC_Pdu_2 2   //
#define DCM_RX_vEcuC_Pdu_3 3   //
#define DCM_RX_vEcuC_Pdu_4 4   //
#define DCM_RX_vEcuC_Pdu_5 5   //
#define DCM_RX_vEcuC_Pdu_6 6   //
#define DCM_RX_vEcuC_Pdu_7 7   //




#define DCM_TX_vEcuC_Pdu_0 0
#define DCM_TX_vEcuC_Pdu_1 1
#define DCM_TX_vEcuC_Pdu_2 2
#define DCM_TX_vEcuC_Pdu_3 3
#define DCM_TX_vEcuC_Pdu_4 4
#define DCM_TX_vEcuC_Pdu_5 5
#define DCM_TX_vEcuC_Pdu_6 6


#define DCM_TX_vProtocol_Pdu_0 0
#define DCM_TX_vProtocol_Pdu_1 1 //bcm 0x7e2
#define DCM_TX_vProtocol_Pdu_2 2 //PEPS 0X795
#define DCM_TX_vProtocol_Pdu_3 3 //TPMS 0X737
#define DCM_TX_vProtocol_Pdu_4 4  //RCM 0X7A2
#define DCM_TX_vProtocol_Pdu_5 5  //HVAC 0X7C6
#define DCM_TX_vProtocol_Pdu_6 6  //IHU 0X7C1


#define USE_PDUR

//do add/subtract by hand.please
#define USE_DEM
#define DCM_USE_SERVICE_DIAGNOSTICSESSIONCONTROL
#define DCM_USE_SERVICE_ECURESET
#define DCM_USE_SERVICE_CLEARDIAGNOSTICINFORMATION
#define DCM_USE_SERVICE_READDTCINFORMATION
#define DCM_USE_SERVICE_READDATABYIDENTIFIER
#define DCM_USE_SERVICE_READMEMORYBYADDRESS
#define DCM_USE_SERVICE_WRITEMEMORYBYADDRESS
#define DCM_USE_SERVICE_READSCALINGDATABYIDENTIFIER
#define DCM_USE_SERVICE_SECURITYACCESS
#define DCM_USE_SERVICE_WRITEDATABYIDENTIFIER
#define DCM_USE_SERVICE_ROUTINECONTROL
#define DCM_USE_SERVICE_TESTERPRESENT
#define DCM_USE_SERVICE_CONTROLDTCSETTING
#define DCM_USE_SERVICE_READDATABYPERIODICIDENTIFIER
//#define DCM_USE_SERVICE_DYNAMICALLYDEFINEDATAIDENTIFIER
#define DCM_USE_SERVICE_INPUTOUTPUTCONTROLBYIDENTIFIER
#define DCM_USE_SERVICE_COMMUNICATIONCONTROL

//#define DCM_USE_SERVICE_REQUESTDOWNLOAD
//#define DCM_USE_SERVICE_TRANSFERDATA
//#define DCM_USE_SERVICE_REQUESTTRANSFEREXIT


#define DCM_MAX_DDDSOURCE_NUMBER 5
#define DCM_MAX_DDD_NUMBER 6
#define DCM_LIMITNUMBER_PERIODDATA 1
#define DCM_PERIODICTRANSMIT_SLOW 10
#define DCM_PERIODICTRANSMIT_MEDIUM 20
#define DCM_PERIODICTRANSMIT_FAST 40

#define DCM_NOF_IOCONTROL_DIDS 6

#define DCM_SECURITY_EOL_INDEX 2

extern uint8_t vDcmBuffer_1_RX[];


#endif /*DCM_CFG_H_*/

