/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-24:09-38-31.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "Std_Types.h"
#include "Dcm.h"
#include "Dcm_Internal.h"
#if defined(USE_PDUR)
#include "PduR.h"
#endif



#define 	SECURITY_NUM_ATT_DELAY 		3
#define 	SECURITY_DELAY_TIME			10000
#define 	SECURITY_DELAY_TIME_ONBOOT	0
#define 	SECURITY_NUM_ATT_LOCK 		0
#define 	SECURITY_ADR_SIZE			0
#define 	SECURITY_SEED_SIZE			4
#define 	SECURITY_KEY_SIZE			4


const Dcm_DspSessionRowType	DspSessionRow[] ={
	{//Default session
		/* DspSessionLevel;			  */ 1,
		/* DspSessionP2ServerMax;	  */ 50,
		/* DspSessionP2StarServerMax; */ 2000,
		/* Arc_EOL;                   */ false,
	},

	{//extended session
		/* DspSessionLevel;			  */ 3,
		/* DspSessionP2ServerMax;	  */ 50,
		/* DspSessionP2StarServerMax; */ 2000,
		/* Arc_EOL;                   */ false,
	},
	
	{//edummy
		/* DspSessionLevel;			  */ 3,
		/* DspSessionP2ServerMax;	  */ 5,
		/* DspSessionP2StarServerMax; */ 5,
		/* Arc_EOL;                   */ TRUE,
	},
};



const Dcm_DspSecurityRowType	DspSecurityRow[]={
	{
		/* DspSecurityADRSize;		   */ SECURITY_ADR_SIZE,
		/* DspSecurityDelayTimeOnBoot; */ SECURITY_DELAY_TIME_ONBOOT,
		/* DspSecurityDelayTime;	   */ SECURITY_DELAY_TIME,
		/* DspSecurityLevel;		   */ DCM_SEC_LEV_LOCKED,
		/* DspSecurityNumAttDelay;	   */ SECURITY_NUM_ATT_DELAY,
		/* DspSecurityNumAttLock;	   */ SECURITY_NUM_ATT_LOCK,
		/* DspSecuritySeedSize;		   */ SECURITY_SEED_SIZE,
		/* DspSecurityKeySize;		   */ SECURITY_KEY_SIZE,
		/* GetSeed;                    */ SecurityAccessGetSeed,
		/* CompareKey;                 */ SecurityAccessCompareKey,
		/* Arc_EOL;                    */ FALSE,
	},

	{
		/* DspSecurityADRSize;		   */ SECURITY_ADR_SIZE,
		/* DspSecurityDelayTimeOnBoot; */ SECURITY_DELAY_TIME_ONBOOT,
		/* DspSecurityDelayTime;	   */ SECURITY_DELAY_TIME,
		/* DspSecurityLevel;		   */ DCM_SEC_LEV_L1,
		/* DspSecurityNumAttDelay;	   */ SECURITY_NUM_ATT_DELAY,
		/* DspSecurityNumAttLock;	   */ SECURITY_NUM_ATT_LOCK,
		/* DspSecuritySeedSize;		   */ SECURITY_SEED_SIZE,
		/* DspSecurityKeySize;		   */ SECURITY_KEY_SIZE,
		/* GetSeed;                    */ SecurityAccessGetSeed,
		/* CompareKey;                 */ SecurityAccessCompareKey,
		/* Arc_EOL;                    */ FALSE,
	},

	{// DUMMY
		/* DspSecurityADRSize;		   */ 0,
		/* DspSecurityDelayTimeOnBoot; */ 0,
		/* DspSecurityDelayTime;	   */ 0,
		/* DspSecurityLevel;		   */ DCM_SEC_LEV_L1,
		/* DspSecurityNumAttDelay;	   */ SECURITY_NUM_ATT_DELAY,
		/* DspSecurityNumAttLock;	   */ SECURITY_NUM_ATT_LOCK,
		/* DspSecuritySeedSize;		   */ SECURITY_SEED_SIZE,
		/* DspSecurityKeySize;		   */ SECURITY_KEY_SIZE,
		/* GetSeed;                    */ NULL,
		/* CompareKey;                 */ NULL,
		/* Arc_EOL;                    */ TRUE,//FALSE,
	},
};




const Dcm_DspSecurityRowType *DspSecurityRow10[] = {
	&DspSecurityRow[2],//DUMMY
};

const Dcm_DspSecurityRowType *DspSecurityRow11[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow27[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow28[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow3E[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow85[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow22[] = {
	&DspSecurityRow[2],//DUMMY
};

const Dcm_DspSecurityRowType *DspSecurityRow2E[] = {
	&DspSecurityRow[1],
	&DspSecurityRow[2],//DUMMY
};

const Dcm_DspSecurityRowType *DspSecurityRow14[] = {
	&DspSecurityRow[2],//DUMMY
};
const Dcm_DspSecurityRowType *DspSecurityRow19[] = {
	&DspSecurityRow[2],//DUMMY,
};
const Dcm_DspSecurityRowType *DspSecurityRow2F[] = {
	&DspSecurityRow[1],

	&DspSecurityRow[2],//DUMMY
};

const Dcm_DspSecurityRowType *DspSecurityRow31[] = {
	&DspSecurityRow[1],
	&DspSecurityRow[2],//DUMMY
};



const Dcm_DspSessionRowType	*DspSessionRow0x10[] = {
    &DspSessionRow[0],
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};

const Dcm_DspSessionRowType	*DspSessionRow0x11[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x27[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x28[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x3E[] = {
    &DspSessionRow[0],
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};

const Dcm_DspSessionRowType	*DspSessionRow0x85[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x22[] = {
    &DspSessionRow[0],
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};


const Dcm_DspSessionRowType	*DspSessionRow0x2E[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};

const Dcm_DspSessionRowType	*DspSessionRow0x14[] = {
    &DspSessionRow[0],
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x19[] = {
    &DspSessionRow[0],
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};

const Dcm_DspSessionRowType	*DspSessionRow0x2F[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};
const Dcm_DspSessionRowType	*DspSessionRow0x31[] = {
	&DspSessionRow[1],
	&DspSessionRow[2],//DUMMY
};


const Dcm_DspDidControlRecordSizesType DspDidControlRecordSizesTypeList={
		0,//.DspDidControlEnableMaskRecordSize=0,
		1,//.DspDidControlOptionRecordSize=1,
		0,//.DspDidControlStatusRecordSize=1,//1,modified,xy,20160720 cancel control state
};

const Dcm_DspDidControlRecordSizesType  DspDidResetToDefaultList={
		0,//.DspDidControlEnableMaskRecordSize=0,
		0,//.DspDidControlOptionRecordSize=0,
		0,//.DspDidControlStatusRecordSize=0,
};

const Dcm_DspDidControlRecordSizesType  DspDidReturnControlToEcuList={
		0,//.DspDidControlEnableMaskRecordSize=0,
		0,//.DspDidControlOptionRecordSize=0,
		1,//.DspDidControlStatusRecordSize=0,
};



const Dcm_DspDidControlType DspDidControlTypeList={
		DspSessionRow0x2F,//.DspDidControlSessionRef=&DspSessionRowTypeListList,
		DspSecurityRow2F,//.DspDidControlSecurityLevelRef=&DspSecurityRowTypeListList0x2F,
		NULL,//.DspDidFreezeCurrentState=NULL,
		&DspDidResetToDefaultList,//.DspDidResetToDefault=&DspDidResetToDefaultList,
		&DspDidReturnControlToEcuList,//.DspDidReturnControlToEcu=&DspDidReturnControlToEcuList,
		&DspDidControlRecordSizesTypeList,//.DspDidShortTermAdjustment=&DspDidControlRecordSizesTypeList,
};

const Dcm_DspDidReadType	Dcm_DspDidReadTypeList={
		DspSessionRow0x22,//.DspDidReadSessionRef=&DspSessionRowTypeListList,
		DspSecurityRow22,//.DspDidReadSecurityLevelRef=&DspSecurityRowTypeListList0x22,
};



const Dcm_DspDidWriteType		Dcm_DspDidWriteTypeList={
		DspSessionRow0x2E,//.DspDidWriteSessionRef=&DspSessionRowTypeListList,
		DspSecurityRow2E,//.DspDidWriteSecurityLevelRef=&DspSecurityRowTypeListList0x2E,
};


const Dcm_DspDidInfoType	DspDidInfoTypeList={
		false,//.DspDidDynamicllyDefined=NULL,
		true,//.DspDidFixedLength,
		0,//.DspDidScalingInfoSize=NULL,
		{
			&Dcm_DspDidReadTypeList,//.DspDidAccess.DspDidRead=&Dcm_DspDidReadTypeList,
			&Dcm_DspDidWriteTypeList,//.DspDidAccess.DspDidWrite=&Dcm_DspDidWriteTypeList,
			&DspDidControlTypeList,//.DspDidAccess.DspDidControl=&DspDidControlTypeList,
		},
};




const Dcm_DspDidType	DspDidTypeList[] =
{	
//========================================================================
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0x0200,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	1,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_0200,
		/* DspDidWriteDataFnc;			 	*/	Write_DidWriteDataFnc_0200,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0x0201,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	1,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_0201,
		/* DspDidWriteDataFnc;			 	*/	Write_DidWriteDataFnc_0201,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0xDF00,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	1,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_DF00,
		/* DspDidWriteDataFnc;			 	*/	NULL/*Write_DidWriteDataFnc_DF00*/,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0xDF01,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	2,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_DF01,
		/* DspDidWriteDataFnc;			 	*/	NULL/*Write_DidWriteDataFnc_DF01*/,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0xF101,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	16,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_F101,
		/* DspDidWriteDataFnc;			 	*/	Write_DidWriteDataFnc_F101,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0xF110,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	8,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_F110,
		/* DspDidWriteDataFnc;			 	*/	Write_DidWriteDataFnc_F110,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
	{
		/* DspDidUsePort;		       	 	*/	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 	*/	0xF112,
		/* *DspDidInfoRef;				 	*/	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 	*/	NULL,	
		/* DspDidSize;					 	*/	8,	
		/* DspDidReadDataLengthFnc;		 	*/	NULL,
		/* DspDidConditionCheckReadFnc;	 	*/	Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 	*/	Read_DidReadDataFnc_F112,
		/* DspDidWriteDataFnc;			 	*/	Write_DidWriteDataFnc_F112,
		/* DspDidGetScalingInfoFnc;		 	*/	NULL,
		/* DspDidFreezeCurrentStateFnc;	 	*/	NULL,
		/* DspDidResetToDefaultFnc;		 	*/	NULL,
		/* DspDidReturnControlToEcuFnc;	 	*/	NULL,
		/* DspDidShortTermAdjustmentFnc; 	*/	NULL,
		/* *DspDidControlRecordSize;	 	*/	NULL,
		/* DspDidHasData;                	*/	TRUE,
		/* Arc_EOL;                     	*/	FALSE,
	},
//========================================================================
	{  //oK
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF187,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	10,	//21,
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F187,
		/* DspDidWriteDataFnc;			 */	NULL,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},		
	{  //OK
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF18A,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	6,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F18A,
		/* DspDidWriteDataFnc;			 */	NULL,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},

	{//OK
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF18C,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	24,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F18C,
		/* DspDidWriteDataFnc;			 */	NULL/*Write_DidWriteDataFnc_F18C*/,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},	
		
	{//OK
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF190,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	17,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F190,
		/* DspDidWriteDataFnc;			 */	Write_DidWriteDataFnc_F190,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},
		
	{
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF191,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	16,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F191,
		/* DspDidWriteDataFnc;			 */	NULL/*Write_DidWriteDataFnc_F191*/,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},

	{
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF193,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	16,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F193,
		/* DspDidWriteDataFnc;			 */	NULL/*Write_DidWriteDataFnc_F193*/,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},	

	{
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF195,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	21,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F195,
		/* DspDidWriteDataFnc;			 */	NULL/*Write_DidWriteDataFnc_F195*/,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},	
		
	{
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF19D,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	4,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_F19D,
		/* DspDidWriteDataFnc;			 */	Write_DidWriteDataFnc_F19D,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},
	{
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0x7960,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	4,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	Read_DidReadDataFnc_7960,
		/* DspDidWriteDataFnc;			 */	NULL,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ Ctrl_DidReturnControlToEcuFnc_7960,
		/* DspDidShortTermAdjustmentFnc; */	Ctrl_DidShortTermAdjustmentFnc_7960,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ FALSE,
	},
    {//dump 
		/* DspDidUsePort;		       	 */	DATA_PORT_SYNCH,			
		/* DspDidIdentifier;			 */	0xF122,
		/* *DspDidInfoRef;				 */	&DspDidInfoTypeList,
		/* * const *DspDidRef;			 */	NULL,	
		/* DspDidSize;					 */	4,	
		/* DspDidReadDataLengthFnc;		 */	NULL,
		/* DspDidConditionCheckReadFnc;	 */ Read_DidConditionCheckReadFnc,
		/* DspDidReadDataFnc;			 */	NULL,
		/* DspDidWriteDataFnc;			 */	NULL,
		/* DspDidGetScalingInfoFnc;		 */ NULL,
		/* DspDidFreezeCurrentStateFnc;	 */ NULL,
		/* DspDidResetToDefaultFnc;		 */ NULL,
		/* DspDidReturnControlToEcuFnc;	 */ NULL,
		/* DspDidShortTermAdjustmentFnc; */	NULL,
		/* *DspDidControlRecordSize;	 */	NULL,
		/* DspDidHasData;                */ TRUE,
		/* Arc_EOL;                      */ TRUE,
	},
};




const Dcm_DspSessionType  Dcm_DspSession = {
    DspSessionRow,
};

const Dcm_DspSecurityType Dcm_DspSecurity = {
	DspSecurityRow,
};


const Dcm_DspType Dsp = {
		0,
		&DspDidTypeList[0],		//.DspDid = &DspDidTypeList[0],
		NULL,					//.DspDidInfo = NULL,
		NULL,					//.DspEcuReset = NULL,
		NULL,					//.DspPid = NULL,
		NULL,					//.DspReadDTC = NULL,
		NULL,					//.DspRequestControl = NULL,
		NULL,					//.DspRoutine = &DspRoutineTypeList,
		NULL,					//.DspRoutineInfo = NULL,
		&Dcm_DspSecurity,		//.DspSecurity = &DspSecurityTypeList,
		&Dcm_DspSession ,		//.DspSession = &DspSessionTypeList,
		NULL,
		NULL,					//.DspTestResultByObdmid = NULL,
		NULL,					//.DspVehInfo = NULL,
};

/* --------------------------------------------------------- */

/************************************************************************
 *									DSD									*
 ************************************************************************/

/************************************************************************
 *									DSL									*
 ************************************************************************/

uint8_t vDcmBuffer_1_RX[124+3];
Dcm_DslBufferRuntimeType BufferParams_vDcmBuffer_1_RX =
{
	/* status = */ BUFFER_AVAILABLE
};
uint8_t vDcmBuffer_1_TX[DCM_BUFFER_TX_SIZE];//>=4*DTC NUMBER+5
Dcm_DslBufferRuntimeType BufferParams_vDcmBuffer_1_TX =
{
	/* status = */ BUFFER_AVAILABLE
};
const Dcm_DslBufferType DcmDslBufferList[DCM_DSL_BUFFER_LIST_LENGTH] = {
	{
		/* DslBufferID;				   */ 0,			
		/* DslBufferSize;			   */ 124,
		/* pduInfo;					   */	
										  {
		/* SduDataPtr  				   */     &vDcmBuffer_1_RX[3],	
		/* SduLength                   */ 	  124,
										  },
		/* *externalBufferRuntimeData; */ &BufferParams_vDcmBuffer_1_RX
	},

	{
		/* DslBufferID;				   */ 1,			
		/* DslBufferSize;			   */ DCM_BUFFER_TX_SIZE,//128,
		/* pduInfo;					   */	
										  {
		/* SduDataPtr  				   */     vDcmBuffer_1_TX,	
		/* SduLength                   */ 	  DCM_BUFFER_TX_SIZE,//128,
										  },
		/* *externalBufferRuntimeData; */ &BufferParams_vDcmBuffer_1_TX
	},
};


const Dcm_DslCallbackDCMRequestServiceType DCMRequestServiceList[] = {
	{ // vRequestService_1
		/* StartProtocol = */ Dcm_CallbackStartProtocolFnc,//vRequestService_1_Start,
		/* StopProtocol = */ NULL,//vRequestService_1_Stop,
		/* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL
		/* StartProtocol = */ NULL,
		/* StopProtocol = */ NULL,
		/* Arc_EOL = */ TRUE
	}
};

extern const Dcm_DslConnectionType DslConnectionList[];
extern const Dcm_DslProtocolRowType DslProtocolRowList[];
extern const Dcm_DslMainConnectionType Dcm_DslMainConnection[];




const Dcm_DslProtocolRxType DcmDslProtocolRxList[] = {
	{// vProtocol_1->vConnection0->vRxChannel0
			/*DslMainConnectionParent*/		&Dcm_DslMainConnection[0],	//0X7c1&7df
			/*DslProtocolAddrType*/			DCM_PROTOCOL_PHYSICAL_ADDR_TYPE,
			/*DcmDslProtocolRxPduId*/			DCM_RX_vEcuC_Pdu_0,
			/*DcmDslProtocolRxChannelId_v4*/	0,		
			/*DcmDslProtocolRxComMChannel*/ 	0,
			/*Arc_EOL*/                     	FALSE
	},
	{// Dummy for EOL
			/*DslMainConnectionParent*/		&Dcm_DslMainConnection[0],	
			/*DslProtocolAddrType*/			DCM_PROTOCOL_FUNCTIONAL_ADDR_TYPE,
			/*DcmDslProtocolRxPduId*/		DCM_RX_vEcuC_Pdu_0,
			/*DcmDslProtocolRxChannelId_v4*/0,		
			/*DcmDslProtocolRxComMChannel*/ 0,
			/*Arc_EOL*/                     TRUE
	}
};

const Dcm_DslProtocolTxType DcmDslProtocolTxList[] = {
	{// for local diagnostic
		/* DslConnectionParent = */    &Dcm_DslMainConnection[0], //0X7C1&7df
		/* DcmDslProtocolTxPduId = */  DCM_TX_vEcuC_Pdu_0,
		/* Arc_EOL = */                FALSE
	},
	{// Dummy for EOL
		/* DslConnectionParent = */    NULL,
		/* DcmDslProtocolTxPduId = */  0xDB,
		/* Arc_EOL = */                TRUE
	}
};


const Dcm_DslMainConnectionType Dcm_DslMainConnection[] = { // Cross referenced from Dcm_DslProtocolRxType_t.
	{
		/*DslConnectionParent*/           &DslConnectionList[0],
		/*DslPeriodicTransmissionConRef*/ NULL,
		/**DslROEConnectionRef*/          NULL,

		/*DslProtocolRx*/                 &DcmDslProtocolRxList[0],   //0X7C1 0X7DF
		/**DslProtocolTx*/                &DcmDslProtocolTxList[0],	//0X7C9			
		/* DslRxTesterSourceAddress*/     0
	}
};

const Dcm_DslConnectionType DslConnectionList[] = {
	{//vProtocol_1->vConnection0
		/* DslProtocolRow */              &DslProtocolRowList[0], 
		/* DslMainConnection */           &Dcm_DslMainConnection[0],
		/* DslPeriodicTransmission */     NULL,
		/*DslResponseOnEvent*/            NULL,
		/* Arc_EOL = */                   FALSE
	},
	{//Dummy For EOL
		/* DslProtocolRow */          &DslProtocolRowList[0],
		/* DslMainConnection */       &Dcm_DslMainConnection[0],
		/* DslPeriodicTransmission */ NULL,
		/*DslResponseOnEvent*/        NULL,
		/* Arc_EOL = */               TRUE
	}
};


 
 


const Dcm_DsdServiceType  DsdServiceTypeList[]={
		{//session control
			/*DsdSidTabServiceId*/   	0x10 ,
			/*DsdSidTabSubfuncAvail*/ 	TRUE,		
			/*DsdSidTabSecurityLevelRef*/  DspSecurityRow10,
			/*DsdSidTabSessionLevelRef*/   DspSessionRow0x10,
            /*ArcDcmDsdSidConditionCheckFnc*/ NULL,
            /*Dcm_DsdResetPidsFncType*/ 	NULL,
			FALSE,
		},
			
		{//ECU Reset
			0x11,//.DsdSidTabServiceId=0x11,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow11,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x11,
			DspSessionRow0x11,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListList,
			NULL,
            NULL,
			FALSE,
		},

		{//security access
			0x27,//.DsdSidTabServiceId=0x27,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow27,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x27,
			DspSessionRow0x27,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListListExtended,
			NULL,
            NULL,
			FALSE,
		},

		{//Test present
			0x3E,//.DsdSidTabServiceId=0x3E,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow3E,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x3E,
			DspSessionRow0x3E,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListList,
			NULL,
            NULL,
			FALSE,
		},

		{//communication control
			0x28,//.DsdSidTabServiceId=0x28,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow28,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x28,
			DspSessionRow0x28,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListListExtended,
			NULL,
            NULL,
			FALSE,
		},

		{// DTC setting
			0x85,//.DsdSidTabServiceId=0x85,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow85,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x85,
			DspSessionRow0x85,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListListExtended,
			NULL,
            NULL,
			FALSE,
		},
		{// read data by identifier
			0x22,//.DsdSidTabServiceId=0x22,
			0,//.DsdSidTabSubfuncAvail=0,
			DspSecurityRow22,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x22,
			DspSessionRow0x22,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListList,
			NULL,
            NULL,
			FALSE,
		},
		{// Write data by identifier
			0x2E,//.DsdSidTabServiceId=0x2E,
			0,//.DsdSidTabSubfuncAvail=0,
			DspSecurityRow2E,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x2E,
			DspSessionRow0x2E,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListListExtended,
			NULL,
            NULL,
			FALSE,
		},
		{ //clear DTC
			0x14,//.DsdSidTabServiceId=0x14,
			0,//.DsdSidTabSubfuncAvail=0,
			DspSecurityRow14,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x14,
			DspSessionRow0x14,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListList,
			NULL,
            NULL,
			FALSE,
		},		
		{//Read DTC
			0x19,//.DsdSidTabServiceId=0x19,
			1,//.DsdSidTabSubfuncAvail=1,
			DspSecurityRow19,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x19,
			DspSessionRow0x19,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListList,
			NULL,
            NULL,
			FALSE,
		},
		
		
		{ // io control
			0x2F,//.DsdSidTabServiceId=0x2F,
			0,//.DsdSidTabSubfuncAvail=0,
			DspSecurityRow2F,//.DsdSidTabSecurityLevelRef=&DspSecurityRowTypeListList0x2F,
			DspSessionRow0x2F,//.DsdSidTabSessionLevelRef=&DspSessionRowTypeListListExtended,
			NULL,
            NULL,
			FALSE,
		},
		{//DUMMY
			0xB0,//.DsdSidTabServiceId=0xB0,
			0,//.DsdSidTabSubfuncAvail=1,
			NULL,//
			NULL,//
			NULL,
            NULL,
			TRUE,
		},
};

const Dcm_DsdServiceTableType  DsdServiceTableTypeList={
			0,//.DsdSidTabId=0,
			&DsdServiceTypeList[0],//.DsdService=&DsdServiceTypeList[0],
			0,//.Arc_EOL=0,
};

const Dcm_DslProtocolTimingRowType DslProtocolTimingRowTypeList={
			50,//.TimStrP2ServerMax=10,
			50,//.TimStrP2ServerMin=10,
			2000,//.TimStrP2StarServerMax=10,
			2000,//.TimStrP2StarServerMin=10,
			5000,//.TimStrS3Server=10,
};

Dcm_DslRunTimeProtocolParametersType dcmDslRuntimeVariables[1];
const Dcm_DslProtocolRowType DslProtocolRowList[]= {
	{//vProtocol_1
		/* DslProtocolID = */                DCM_UDS_ON_CAN,
		/*DslProtocolIsParallelExecutab*/    TRUE,
		/*DslProtocolPreemptTimeout*/        100,
		/*DslProtocolPriority*/              1,
		/*DslProtocolTransType*/             DCM_PROTOCOL_TRANS_TYPE_1,
		/* DslProtocolRxBufferID */          &DcmDslBufferList[0],//vDcmBuffer_1_RX
		/* DslProtocolTxBufferID = */        &DcmDslBufferList[1],//vDcmBuffer_1_TX
		/*DslProtocolSIDTable*/              &DsdServiceTableTypeList,
		/*DslProtocolTimeLimit*/             &DslProtocolTimingRowTypeList,
		/* DslConnection = */                &DslConnectionList[0],
		/* DslRunTimeProtocolParameters = */ &dcmDslRuntimeVariables[0],
		/* Arc_EOL = */ FALSE
	},
	{//Dummy for EOL
		/* DslProtocolID = */                0,
		/*DslProtocolIsParallelExecutab*/    TRUE,
		/*DslProtocolPreemptTimeout*/        100,
		/*DslProtocolPriority*/              1,
		/*DslProtocolTransType*/             DCM_PROTOCOL_TRANS_TYPE_1,
		/* DslProtocolRxBufferID */          &DcmDslBufferList[0],//vDcmBuffer_1_RX
		/* DslProtocolTxBufferID = */        &DcmDslBufferList[1],//vDcmBuffer_1_TX
		/*DslProtocolSIDTable*/              NULL,
		/*DslProtocolTimeLimit*/             NULL,
		/* DslConnection = */                DslConnectionList,
		/* DslRunTimeProtocolParameters = */ &dcmDslRuntimeVariables[0],
		/* Arc_EOL = */ TRUE
	}
};

const Dcm_DslProtocolType DslProtocol = {
    /* DslProtocolRxGlobalList = */      DcmDslProtocolRxList,
    /* DslProtocolTxGlobalList = */      DcmDslProtocolTxList,
    /* DslProtocolPeriodicTxGlobalList*/ NULL,    
    /* DslProtocolRowList = */           DslProtocolRowList
};
const Dcm_DslSessionControlType Dcm_DslSessionControl[] ={
	{
	/*Dcm_CallbackGetSesChgPermissionFncType*/	NULL,
	/*Dcm_CallbackChangeIndicationFncType	*/	NULL,
	/*Dcm_CallbackConfirmationRespPendFncType*/	NULL,
	/*	Arc_EOL */                          TRUE,
    },
} ; /** @req DCM680 */

const Dcm_DslDiagRespType DslDiagRespTypeList={
		1,//.DslDiagRespForceRespPendEn=1,
		1,//.DslDiagRespMaxNumRespPend=2,
};

const Dcm_DslType Dsl = {
    /* DslBuffer  					*/ DcmDslBufferList,
    /* DslCallbackDCMRequestService */ DCMRequestServiceList,
    /* DslDiagresp					*/ &DslDiagRespTypeList,
    /* DslProtocol 					*/ &DslProtocol,
    /* DslProtocolTiming			*/ NULL,
//  /* DslServiceRequestIndication	*/ NULL,
    /* DslSessionControl			*/ Dcm_DslSessionControl
};

const Dcm_ConfigType DCM_Config = {
	/*Dsp*/ &Dsp,
    /*Dsd*/ NULL,
    /*Dsl*/ &Dsl
};



